/********************************************************************************
** Form generated from reading UI file 'maingame.ui'
**
** Created by: Qt User Interface Compiler version 5.11.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINGAME_H
#define UI_MAINGAME_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainGame
{
public:
    QWidget *centralwidget;
    QPushButton *enemyA1;
    QPushButton *enemyB1;
    QPushButton *enemyC1;
    QPushButton *enemyD1;
    QPushButton *enemyE1;
    QPushButton *enemyF1;
    QPushButton *enemyG1;
    QPushButton *enemyH1;
    QPushButton *enemyI1;
    QPushButton *enemyJ1;
    QPushButton *enemyF2;
    QPushButton *enemyC2;
    QPushButton *enemyH2;
    QPushButton *enemyE2;
    QPushButton *enemyA2;
    QPushButton *enemyG2;
    QPushButton *enemyI2;
    QPushButton *enemyD2;
    QPushButton *enemyB2;
    QPushButton *enemyJ2;
    QPushButton *enemyF3;
    QPushButton *enemyC3;
    QPushButton *enemyH3;
    QPushButton *enemyE3;
    QPushButton *enemyA3;
    QPushButton *enemyG3;
    QPushButton *enemyI3;
    QPushButton *enemyD3;
    QPushButton *enemyB3;
    QPushButton *enemyJ3;
    QPushButton *enemyF4;
    QPushButton *enemyC4;
    QPushButton *enemyH4;
    QPushButton *enemyE4;
    QPushButton *enemyA4;
    QPushButton *enemyG4;
    QPushButton *enemyI4;
    QPushButton *enemyD4;
    QPushButton *enemyB4;
    QPushButton *enemyJ4;
    QPushButton *enemyF5;
    QPushButton *enemyC5;
    QPushButton *enemyH5;
    QPushButton *enemyE5;
    QPushButton *enemyA5;
    QPushButton *enemyG5;
    QPushButton *enemyI5;
    QPushButton *enemyD5;
    QPushButton *enemyB5;
    QPushButton *enemyJ5;
    QPushButton *enemyF6;
    QPushButton *enemyC6;
    QPushButton *enemyH6;
    QPushButton *enemyE6;
    QPushButton *enemyA6;
    QPushButton *enemyG6;
    QPushButton *enemyI6;
    QPushButton *enemyD6;
    QPushButton *enemyB6;
    QPushButton *enemyJ6;
    QPushButton *enemyF7;
    QPushButton *enemyC7;
    QPushButton *enemyH7;
    QPushButton *enemyE7;
    QPushButton *enemyA7;
    QPushButton *enemyG7;
    QPushButton *enemyI7;
    QPushButton *enemyD7;
    QPushButton *enemyB7;
    QPushButton *enemyJ7;
    QPushButton *enemyF8;
    QPushButton *enemyC8;
    QPushButton *enemyH8;
    QPushButton *enemyE8;
    QPushButton *enemyA8;
    QPushButton *enemyG8;
    QPushButton *enemyI8;
    QPushButton *enemyD8;
    QPushButton *enemyB8;
    QPushButton *enemyJ8;
    QPushButton *enemyF9;
    QPushButton *enemyC9;
    QPushButton *enemyH9;
    QPushButton *enemyE9;
    QPushButton *enemyA9;
    QPushButton *enemyG9;
    QPushButton *enemyI9;
    QPushButton *enemyD9;
    QPushButton *enemyB9;
    QPushButton *enemyJ9;
    QPushButton *enemyF10;
    QPushButton *enemyC10;
    QPushButton *enemyH10;
    QPushButton *enemyE10;
    QPushButton *enemyA10;
    QPushButton *enemyG10;
    QPushButton *enemyI10;
    QPushButton *enemyD10;
    QPushButton *enemyB10;
    QPushButton *enemyJ10;
    QPushButton *meF1;
    QPushButton *meC1;
    QPushButton *meH1;
    QPushButton *meE1;
    QPushButton *meA1;
    QPushButton *meG1;
    QPushButton *meI1;
    QPushButton *meD1;
    QPushButton *meB1;
    QPushButton *meJ1;
    QPushButton *meF2;
    QPushButton *meC2;
    QPushButton *meH2;
    QPushButton *meE2;
    QPushButton *meA2;
    QPushButton *meG2;
    QPushButton *meI2;
    QPushButton *meD2;
    QPushButton *meB2;
    QPushButton *meJ2;
    QPushButton *meF3;
    QPushButton *meC3;
    QPushButton *meH3;
    QPushButton *meE3;
    QPushButton *meA3;
    QPushButton *meG3;
    QPushButton *meI3;
    QPushButton *meD3;
    QPushButton *meB3;
    QPushButton *meJ3;
    QPushButton *meF4;
    QPushButton *meC4;
    QPushButton *meH4;
    QPushButton *meE4;
    QPushButton *meA4;
    QPushButton *meG4;
    QPushButton *meI4;
    QPushButton *meD4;
    QPushButton *meB4;
    QPushButton *meJ4;
    QPushButton *meF5;
    QPushButton *meC5;
    QPushButton *meH5;
    QPushButton *meE5;
    QPushButton *meA5;
    QPushButton *meG5;
    QPushButton *meI5;
    QPushButton *meD5;
    QPushButton *meB5;
    QPushButton *meJ5;
    QPushButton *meF6;
    QPushButton *meC6;
    QPushButton *meH6;
    QPushButton *meE6;
    QPushButton *meA6;
    QPushButton *meG6;
    QPushButton *meI6;
    QPushButton *meD6;
    QPushButton *meB6;
    QPushButton *meJ6;
    QPushButton *meF7;
    QPushButton *meC7;
    QPushButton *meH7;
    QPushButton *meE7;
    QPushButton *meG7;
    QPushButton *meI7;
    QPushButton *meD7;
    QPushButton *meB7;
    QPushButton *meJ7;
    QPushButton *meF8;
    QPushButton *meC8;
    QPushButton *meH8;
    QPushButton *meE8;
    QPushButton *meA8;
    QPushButton *meG8;
    QPushButton *meI8;
    QPushButton *meD8;
    QPushButton *meB8;
    QPushButton *meJ8;
    QPushButton *meF9;
    QPushButton *meC9;
    QPushButton *meH9;
    QPushButton *meE9;
    QPushButton *meA9;
    QPushButton *meG9;
    QPushButton *meI9;
    QPushButton *meD9;
    QPushButton *meB9;
    QPushButton *meJ9;
    QPushButton *meF10;
    QPushButton *meC10;
    QPushButton *meH10;
    QPushButton *meE10;
    QPushButton *meA10;
    QPushButton *meG10;
    QPushButton *meI10;
    QPushButton *meD10;
    QPushButton *meB10;
    QPushButton *meJ10;
    QPushButton *battleship1;
    QPushButton *battleship2;
    QPushButton *battleship3_1;
    QPushButton *battleship3_2;
    QPushButton *battleship4;
    QPushButton *battleship5;
    QLabel *label;
    QLabel *label_2;
    QPushButton *meA7;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLineEdit *lineEdit_26;
    QLineEdit *lineEdit_27;
    QLineEdit *lineEdit_28;
    QLineEdit *lineEdit_29;
    QLineEdit *lineEdit_30;
    QLineEdit *lineEdit_31;
    QLineEdit *lineEdit_32;
    QLineEdit *lineEdit_33;
    QLineEdit *lineEdit_34;
    QLineEdit *lineEdit_35;
    QLineEdit *lineEdit_36;
    QLineEdit *lineEdit_37;
    QLineEdit *lineEdit_38;
    QLineEdit *lineEdit_39;
    QLineEdit *lineEdit_40;
    QLineEdit *lineEdit_41;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainGame)
    {
        if (MainGame->objectName().isEmpty())
            MainGame->setObjectName(QStringLiteral("MainGame"));
        MainGame->resize(1550, 900);
        centralwidget = new QWidget(MainGame);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        enemyA1 = new QPushButton(centralwidget);
        enemyA1->setObjectName(QStringLiteral("enemyA1"));
        enemyA1->setGeometry(QRect(50, 50, 50, 50));
        enemyA1->setMaximumSize(QSize(50, 50));
        enemyB1 = new QPushButton(centralwidget);
        enemyB1->setObjectName(QStringLiteral("enemyB1"));
        enemyB1->setGeometry(QRect(100, 50, 50, 50));
        enemyB1->setMaximumSize(QSize(50, 50));
        enemyC1 = new QPushButton(centralwidget);
        enemyC1->setObjectName(QStringLiteral("enemyC1"));
        enemyC1->setGeometry(QRect(150, 50, 50, 50));
        enemyC1->setMaximumSize(QSize(50, 50));
        enemyD1 = new QPushButton(centralwidget);
        enemyD1->setObjectName(QStringLiteral("enemyD1"));
        enemyD1->setGeometry(QRect(200, 50, 50, 50));
        enemyD1->setMaximumSize(QSize(50, 50));
        enemyE1 = new QPushButton(centralwidget);
        enemyE1->setObjectName(QStringLiteral("enemyE1"));
        enemyE1->setGeometry(QRect(250, 50, 50, 50));
        enemyE1->setMaximumSize(QSize(50, 50));
        enemyF1 = new QPushButton(centralwidget);
        enemyF1->setObjectName(QStringLiteral("enemyF1"));
        enemyF1->setGeometry(QRect(300, 50, 50, 50));
        enemyF1->setMaximumSize(QSize(50, 50));
        enemyG1 = new QPushButton(centralwidget);
        enemyG1->setObjectName(QStringLiteral("enemyG1"));
        enemyG1->setGeometry(QRect(350, 50, 50, 50));
        enemyG1->setMaximumSize(QSize(50, 50));
        enemyH1 = new QPushButton(centralwidget);
        enemyH1->setObjectName(QStringLiteral("enemyH1"));
        enemyH1->setGeometry(QRect(400, 50, 50, 50));
        enemyH1->setMaximumSize(QSize(50, 50));
        enemyI1 = new QPushButton(centralwidget);
        enemyI1->setObjectName(QStringLiteral("enemyI1"));
        enemyI1->setGeometry(QRect(450, 50, 50, 50));
        enemyI1->setMaximumSize(QSize(50, 50));
        enemyJ1 = new QPushButton(centralwidget);
        enemyJ1->setObjectName(QStringLiteral("enemyJ1"));
        enemyJ1->setGeometry(QRect(500, 50, 50, 50));
        enemyJ1->setMaximumSize(QSize(50, 50));
        enemyF2 = new QPushButton(centralwidget);
        enemyF2->setObjectName(QStringLiteral("enemyF2"));
        enemyF2->setGeometry(QRect(300, 100, 50, 50));
        enemyF2->setMaximumSize(QSize(50, 50));
        enemyC2 = new QPushButton(centralwidget);
        enemyC2->setObjectName(QStringLiteral("enemyC2"));
        enemyC2->setGeometry(QRect(150, 100, 50, 50));
        enemyC2->setMaximumSize(QSize(50, 50));
        enemyH2 = new QPushButton(centralwidget);
        enemyH2->setObjectName(QStringLiteral("enemyH2"));
        enemyH2->setGeometry(QRect(400, 100, 50, 50));
        enemyH2->setMaximumSize(QSize(50, 50));
        enemyE2 = new QPushButton(centralwidget);
        enemyE2->setObjectName(QStringLiteral("enemyE2"));
        enemyE2->setGeometry(QRect(250, 100, 50, 50));
        enemyE2->setMaximumSize(QSize(50, 50));
        enemyA2 = new QPushButton(centralwidget);
        enemyA2->setObjectName(QStringLiteral("enemyA2"));
        enemyA2->setGeometry(QRect(50, 100, 50, 50));
        enemyA2->setMaximumSize(QSize(50, 50));
        enemyG2 = new QPushButton(centralwidget);
        enemyG2->setObjectName(QStringLiteral("enemyG2"));
        enemyG2->setGeometry(QRect(350, 100, 50, 50));
        enemyG2->setMaximumSize(QSize(50, 50));
        enemyI2 = new QPushButton(centralwidget);
        enemyI2->setObjectName(QStringLiteral("enemyI2"));
        enemyI2->setGeometry(QRect(450, 100, 50, 50));
        enemyI2->setMaximumSize(QSize(50, 50));
        enemyD2 = new QPushButton(centralwidget);
        enemyD2->setObjectName(QStringLiteral("enemyD2"));
        enemyD2->setGeometry(QRect(200, 100, 50, 50));
        enemyD2->setMaximumSize(QSize(50, 50));
        enemyB2 = new QPushButton(centralwidget);
        enemyB2->setObjectName(QStringLiteral("enemyB2"));
        enemyB2->setGeometry(QRect(100, 100, 50, 50));
        enemyB2->setMaximumSize(QSize(50, 50));
        enemyJ2 = new QPushButton(centralwidget);
        enemyJ2->setObjectName(QStringLiteral("enemyJ2"));
        enemyJ2->setGeometry(QRect(500, 100, 50, 50));
        enemyJ2->setMaximumSize(QSize(50, 50));
        enemyF3 = new QPushButton(centralwidget);
        enemyF3->setObjectName(QStringLiteral("enemyF3"));
        enemyF3->setGeometry(QRect(300, 150, 50, 50));
        enemyF3->setMaximumSize(QSize(50, 50));
        enemyC3 = new QPushButton(centralwidget);
        enemyC3->setObjectName(QStringLiteral("enemyC3"));
        enemyC3->setGeometry(QRect(150, 150, 50, 50));
        enemyC3->setMaximumSize(QSize(50, 50));
        enemyH3 = new QPushButton(centralwidget);
        enemyH3->setObjectName(QStringLiteral("enemyH3"));
        enemyH3->setGeometry(QRect(400, 150, 50, 50));
        enemyH3->setMaximumSize(QSize(50, 50));
        enemyE3 = new QPushButton(centralwidget);
        enemyE3->setObjectName(QStringLiteral("enemyE3"));
        enemyE3->setGeometry(QRect(250, 150, 50, 50));
        enemyE3->setMaximumSize(QSize(50, 50));
        enemyA3 = new QPushButton(centralwidget);
        enemyA3->setObjectName(QStringLiteral("enemyA3"));
        enemyA3->setGeometry(QRect(50, 150, 50, 50));
        enemyA3->setMaximumSize(QSize(50, 50));
        enemyG3 = new QPushButton(centralwidget);
        enemyG3->setObjectName(QStringLiteral("enemyG3"));
        enemyG3->setGeometry(QRect(350, 150, 50, 50));
        enemyG3->setMaximumSize(QSize(50, 50));
        enemyI3 = new QPushButton(centralwidget);
        enemyI3->setObjectName(QStringLiteral("enemyI3"));
        enemyI3->setGeometry(QRect(450, 150, 50, 50));
        enemyI3->setMaximumSize(QSize(50, 50));
        enemyD3 = new QPushButton(centralwidget);
        enemyD3->setObjectName(QStringLiteral("enemyD3"));
        enemyD3->setGeometry(QRect(200, 150, 50, 50));
        enemyD3->setMaximumSize(QSize(50, 50));
        enemyB3 = new QPushButton(centralwidget);
        enemyB3->setObjectName(QStringLiteral("enemyB3"));
        enemyB3->setGeometry(QRect(100, 150, 50, 50));
        enemyB3->setMaximumSize(QSize(50, 50));
        enemyJ3 = new QPushButton(centralwidget);
        enemyJ3->setObjectName(QStringLiteral("enemyJ3"));
        enemyJ3->setGeometry(QRect(500, 150, 50, 50));
        enemyJ3->setMaximumSize(QSize(50, 50));
        enemyF4 = new QPushButton(centralwidget);
        enemyF4->setObjectName(QStringLiteral("enemyF4"));
        enemyF4->setGeometry(QRect(300, 200, 50, 50));
        enemyF4->setMaximumSize(QSize(50, 50));
        enemyC4 = new QPushButton(centralwidget);
        enemyC4->setObjectName(QStringLiteral("enemyC4"));
        enemyC4->setGeometry(QRect(150, 200, 50, 50));
        enemyC4->setMaximumSize(QSize(50, 50));
        enemyH4 = new QPushButton(centralwidget);
        enemyH4->setObjectName(QStringLiteral("enemyH4"));
        enemyH4->setGeometry(QRect(400, 200, 50, 50));
        enemyH4->setMaximumSize(QSize(50, 50));
        enemyE4 = new QPushButton(centralwidget);
        enemyE4->setObjectName(QStringLiteral("enemyE4"));
        enemyE4->setGeometry(QRect(250, 200, 50, 50));
        enemyE4->setMaximumSize(QSize(50, 50));
        enemyA4 = new QPushButton(centralwidget);
        enemyA4->setObjectName(QStringLiteral("enemyA4"));
        enemyA4->setGeometry(QRect(50, 200, 50, 50));
        enemyA4->setMaximumSize(QSize(50, 50));
        enemyG4 = new QPushButton(centralwidget);
        enemyG4->setObjectName(QStringLiteral("enemyG4"));
        enemyG4->setGeometry(QRect(350, 200, 50, 50));
        enemyG4->setMaximumSize(QSize(50, 50));
        enemyI4 = new QPushButton(centralwidget);
        enemyI4->setObjectName(QStringLiteral("enemyI4"));
        enemyI4->setGeometry(QRect(450, 200, 50, 50));
        enemyI4->setMaximumSize(QSize(50, 50));
        enemyD4 = new QPushButton(centralwidget);
        enemyD4->setObjectName(QStringLiteral("enemyD4"));
        enemyD4->setGeometry(QRect(200, 200, 50, 50));
        enemyD4->setMaximumSize(QSize(50, 50));
        enemyB4 = new QPushButton(centralwidget);
        enemyB4->setObjectName(QStringLiteral("enemyB4"));
        enemyB4->setGeometry(QRect(100, 200, 50, 50));
        enemyB4->setMaximumSize(QSize(50, 50));
        enemyJ4 = new QPushButton(centralwidget);
        enemyJ4->setObjectName(QStringLiteral("enemyJ4"));
        enemyJ4->setGeometry(QRect(500, 200, 50, 50));
        enemyJ4->setMaximumSize(QSize(50, 50));
        enemyF5 = new QPushButton(centralwidget);
        enemyF5->setObjectName(QStringLiteral("enemyF5"));
        enemyF5->setGeometry(QRect(300, 250, 50, 50));
        enemyF5->setMaximumSize(QSize(50, 50));
        enemyC5 = new QPushButton(centralwidget);
        enemyC5->setObjectName(QStringLiteral("enemyC5"));
        enemyC5->setGeometry(QRect(150, 250, 50, 50));
        enemyC5->setMaximumSize(QSize(50, 50));
        enemyH5 = new QPushButton(centralwidget);
        enemyH5->setObjectName(QStringLiteral("enemyH5"));
        enemyH5->setGeometry(QRect(400, 250, 50, 50));
        enemyH5->setMaximumSize(QSize(50, 50));
        enemyE5 = new QPushButton(centralwidget);
        enemyE5->setObjectName(QStringLiteral("enemyE5"));
        enemyE5->setGeometry(QRect(250, 250, 50, 50));
        enemyE5->setMaximumSize(QSize(50, 50));
        enemyA5 = new QPushButton(centralwidget);
        enemyA5->setObjectName(QStringLiteral("enemyA5"));
        enemyA5->setGeometry(QRect(50, 250, 50, 50));
        enemyA5->setMaximumSize(QSize(50, 50));
        enemyG5 = new QPushButton(centralwidget);
        enemyG5->setObjectName(QStringLiteral("enemyG5"));
        enemyG5->setGeometry(QRect(350, 250, 50, 50));
        enemyG5->setMaximumSize(QSize(50, 50));
        enemyI5 = new QPushButton(centralwidget);
        enemyI5->setObjectName(QStringLiteral("enemyI5"));
        enemyI5->setGeometry(QRect(450, 250, 50, 50));
        enemyI5->setMaximumSize(QSize(50, 50));
        enemyD5 = new QPushButton(centralwidget);
        enemyD5->setObjectName(QStringLiteral("enemyD5"));
        enemyD5->setGeometry(QRect(200, 250, 50, 50));
        enemyD5->setMaximumSize(QSize(50, 50));
        enemyB5 = new QPushButton(centralwidget);
        enemyB5->setObjectName(QStringLiteral("enemyB5"));
        enemyB5->setGeometry(QRect(100, 250, 50, 50));
        enemyB5->setMaximumSize(QSize(50, 50));
        enemyJ5 = new QPushButton(centralwidget);
        enemyJ5->setObjectName(QStringLiteral("enemyJ5"));
        enemyJ5->setGeometry(QRect(500, 250, 50, 50));
        enemyJ5->setMaximumSize(QSize(50, 50));
        enemyF6 = new QPushButton(centralwidget);
        enemyF6->setObjectName(QStringLiteral("enemyF6"));
        enemyF6->setGeometry(QRect(300, 300, 50, 50));
        enemyF6->setMaximumSize(QSize(50, 50));
        enemyC6 = new QPushButton(centralwidget);
        enemyC6->setObjectName(QStringLiteral("enemyC6"));
        enemyC6->setGeometry(QRect(150, 300, 50, 50));
        enemyC6->setMaximumSize(QSize(50, 50));
        enemyH6 = new QPushButton(centralwidget);
        enemyH6->setObjectName(QStringLiteral("enemyH6"));
        enemyH6->setGeometry(QRect(400, 300, 50, 50));
        enemyH6->setMaximumSize(QSize(50, 50));
        enemyE6 = new QPushButton(centralwidget);
        enemyE6->setObjectName(QStringLiteral("enemyE6"));
        enemyE6->setGeometry(QRect(250, 300, 50, 50));
        enemyE6->setMaximumSize(QSize(50, 50));
        enemyA6 = new QPushButton(centralwidget);
        enemyA6->setObjectName(QStringLiteral("enemyA6"));
        enemyA6->setGeometry(QRect(50, 300, 50, 50));
        enemyA6->setMaximumSize(QSize(50, 50));
        enemyG6 = new QPushButton(centralwidget);
        enemyG6->setObjectName(QStringLiteral("enemyG6"));
        enemyG6->setGeometry(QRect(350, 300, 50, 50));
        enemyG6->setMaximumSize(QSize(50, 50));
        enemyI6 = new QPushButton(centralwidget);
        enemyI6->setObjectName(QStringLiteral("enemyI6"));
        enemyI6->setGeometry(QRect(450, 300, 50, 50));
        enemyI6->setMaximumSize(QSize(50, 50));
        enemyD6 = new QPushButton(centralwidget);
        enemyD6->setObjectName(QStringLiteral("enemyD6"));
        enemyD6->setGeometry(QRect(200, 300, 50, 50));
        enemyD6->setMaximumSize(QSize(50, 50));
        enemyB6 = new QPushButton(centralwidget);
        enemyB6->setObjectName(QStringLiteral("enemyB6"));
        enemyB6->setGeometry(QRect(100, 300, 50, 50));
        enemyB6->setMaximumSize(QSize(50, 50));
        enemyJ6 = new QPushButton(centralwidget);
        enemyJ6->setObjectName(QStringLiteral("enemyJ6"));
        enemyJ6->setGeometry(QRect(500, 300, 50, 50));
        enemyJ6->setMaximumSize(QSize(50, 50));
        enemyF7 = new QPushButton(centralwidget);
        enemyF7->setObjectName(QStringLiteral("enemyF7"));
        enemyF7->setGeometry(QRect(300, 350, 50, 50));
        enemyF7->setMaximumSize(QSize(50, 50));
        enemyC7 = new QPushButton(centralwidget);
        enemyC7->setObjectName(QStringLiteral("enemyC7"));
        enemyC7->setGeometry(QRect(150, 350, 50, 50));
        enemyC7->setMaximumSize(QSize(50, 50));
        enemyH7 = new QPushButton(centralwidget);
        enemyH7->setObjectName(QStringLiteral("enemyH7"));
        enemyH7->setGeometry(QRect(400, 350, 50, 50));
        enemyH7->setMaximumSize(QSize(50, 50));
        enemyE7 = new QPushButton(centralwidget);
        enemyE7->setObjectName(QStringLiteral("enemyE7"));
        enemyE7->setGeometry(QRect(250, 350, 50, 50));
        enemyE7->setMaximumSize(QSize(50, 50));
        enemyA7 = new QPushButton(centralwidget);
        enemyA7->setObjectName(QStringLiteral("enemyA7"));
        enemyA7->setGeometry(QRect(50, 350, 50, 50));
        enemyA7->setMaximumSize(QSize(50, 50));
        enemyG7 = new QPushButton(centralwidget);
        enemyG7->setObjectName(QStringLiteral("enemyG7"));
        enemyG7->setGeometry(QRect(350, 350, 50, 50));
        enemyG7->setMaximumSize(QSize(50, 50));
        enemyI7 = new QPushButton(centralwidget);
        enemyI7->setObjectName(QStringLiteral("enemyI7"));
        enemyI7->setGeometry(QRect(450, 350, 50, 50));
        enemyI7->setMaximumSize(QSize(50, 50));
        enemyD7 = new QPushButton(centralwidget);
        enemyD7->setObjectName(QStringLiteral("enemyD7"));
        enemyD7->setGeometry(QRect(200, 350, 50, 50));
        enemyD7->setMaximumSize(QSize(50, 50));
        enemyB7 = new QPushButton(centralwidget);
        enemyB7->setObjectName(QStringLiteral("enemyB7"));
        enemyB7->setGeometry(QRect(100, 350, 50, 50));
        enemyB7->setMaximumSize(QSize(50, 50));
        enemyJ7 = new QPushButton(centralwidget);
        enemyJ7->setObjectName(QStringLiteral("enemyJ7"));
        enemyJ7->setGeometry(QRect(500, 350, 50, 50));
        enemyJ7->setMaximumSize(QSize(50, 50));
        enemyF8 = new QPushButton(centralwidget);
        enemyF8->setObjectName(QStringLiteral("enemyF8"));
        enemyF8->setGeometry(QRect(300, 400, 50, 50));
        enemyF8->setMaximumSize(QSize(50, 50));
        enemyC8 = new QPushButton(centralwidget);
        enemyC8->setObjectName(QStringLiteral("enemyC8"));
        enemyC8->setGeometry(QRect(150, 400, 50, 50));
        enemyC8->setMaximumSize(QSize(50, 50));
        enemyH8 = new QPushButton(centralwidget);
        enemyH8->setObjectName(QStringLiteral("enemyH8"));
        enemyH8->setGeometry(QRect(400, 400, 50, 50));
        enemyH8->setMaximumSize(QSize(50, 50));
        enemyE8 = new QPushButton(centralwidget);
        enemyE8->setObjectName(QStringLiteral("enemyE8"));
        enemyE8->setGeometry(QRect(250, 400, 50, 50));
        enemyE8->setMaximumSize(QSize(50, 50));
        enemyA8 = new QPushButton(centralwidget);
        enemyA8->setObjectName(QStringLiteral("enemyA8"));
        enemyA8->setGeometry(QRect(50, 400, 50, 50));
        enemyA8->setMaximumSize(QSize(50, 50));
        enemyG8 = new QPushButton(centralwidget);
        enemyG8->setObjectName(QStringLiteral("enemyG8"));
        enemyG8->setGeometry(QRect(350, 400, 50, 50));
        enemyG8->setMaximumSize(QSize(50, 50));
        enemyI8 = new QPushButton(centralwidget);
        enemyI8->setObjectName(QStringLiteral("enemyI8"));
        enemyI8->setGeometry(QRect(450, 400, 50, 50));
        enemyI8->setMaximumSize(QSize(50, 50));
        enemyD8 = new QPushButton(centralwidget);
        enemyD8->setObjectName(QStringLiteral("enemyD8"));
        enemyD8->setGeometry(QRect(200, 400, 50, 50));
        enemyD8->setMaximumSize(QSize(50, 50));
        enemyB8 = new QPushButton(centralwidget);
        enemyB8->setObjectName(QStringLiteral("enemyB8"));
        enemyB8->setGeometry(QRect(100, 400, 50, 50));
        enemyB8->setMaximumSize(QSize(50, 50));
        enemyJ8 = new QPushButton(centralwidget);
        enemyJ8->setObjectName(QStringLiteral("enemyJ8"));
        enemyJ8->setGeometry(QRect(500, 400, 50, 50));
        enemyJ8->setMaximumSize(QSize(50, 50));
        enemyF9 = new QPushButton(centralwidget);
        enemyF9->setObjectName(QStringLiteral("enemyF9"));
        enemyF9->setGeometry(QRect(300, 450, 50, 50));
        enemyF9->setMaximumSize(QSize(50, 50));
        enemyC9 = new QPushButton(centralwidget);
        enemyC9->setObjectName(QStringLiteral("enemyC9"));
        enemyC9->setGeometry(QRect(150, 450, 50, 50));
        enemyC9->setMaximumSize(QSize(50, 50));
        enemyH9 = new QPushButton(centralwidget);
        enemyH9->setObjectName(QStringLiteral("enemyH9"));
        enemyH9->setGeometry(QRect(400, 450, 50, 50));
        enemyH9->setMaximumSize(QSize(50, 50));
        enemyE9 = new QPushButton(centralwidget);
        enemyE9->setObjectName(QStringLiteral("enemyE9"));
        enemyE9->setGeometry(QRect(250, 450, 50, 50));
        enemyE9->setMaximumSize(QSize(50, 50));
        enemyA9 = new QPushButton(centralwidget);
        enemyA9->setObjectName(QStringLiteral("enemyA9"));
        enemyA9->setGeometry(QRect(50, 450, 50, 50));
        enemyA9->setMaximumSize(QSize(50, 50));
        enemyG9 = new QPushButton(centralwidget);
        enemyG9->setObjectName(QStringLiteral("enemyG9"));
        enemyG9->setGeometry(QRect(350, 450, 50, 50));
        enemyG9->setMaximumSize(QSize(50, 50));
        enemyI9 = new QPushButton(centralwidget);
        enemyI9->setObjectName(QStringLiteral("enemyI9"));
        enemyI9->setGeometry(QRect(450, 450, 50, 50));
        enemyI9->setMaximumSize(QSize(50, 50));
        enemyD9 = new QPushButton(centralwidget);
        enemyD9->setObjectName(QStringLiteral("enemyD9"));
        enemyD9->setGeometry(QRect(200, 450, 50, 50));
        enemyD9->setMaximumSize(QSize(50, 50));
        enemyB9 = new QPushButton(centralwidget);
        enemyB9->setObjectName(QStringLiteral("enemyB9"));
        enemyB9->setGeometry(QRect(100, 450, 50, 50));
        enemyB9->setMaximumSize(QSize(50, 50));
        enemyJ9 = new QPushButton(centralwidget);
        enemyJ9->setObjectName(QStringLiteral("enemyJ9"));
        enemyJ9->setGeometry(QRect(500, 450, 50, 50));
        enemyJ9->setMaximumSize(QSize(50, 50));
        enemyF10 = new QPushButton(centralwidget);
        enemyF10->setObjectName(QStringLiteral("enemyF10"));
        enemyF10->setGeometry(QRect(300, 500, 50, 50));
        enemyF10->setMaximumSize(QSize(50, 50));
        enemyC10 = new QPushButton(centralwidget);
        enemyC10->setObjectName(QStringLiteral("enemyC10"));
        enemyC10->setGeometry(QRect(150, 500, 50, 50));
        enemyC10->setMaximumSize(QSize(50, 50));
        enemyH10 = new QPushButton(centralwidget);
        enemyH10->setObjectName(QStringLiteral("enemyH10"));
        enemyH10->setGeometry(QRect(400, 500, 50, 50));
        enemyH10->setMaximumSize(QSize(50, 50));
        enemyE10 = new QPushButton(centralwidget);
        enemyE10->setObjectName(QStringLiteral("enemyE10"));
        enemyE10->setGeometry(QRect(250, 500, 50, 50));
        enemyE10->setMaximumSize(QSize(50, 50));
        enemyA10 = new QPushButton(centralwidget);
        enemyA10->setObjectName(QStringLiteral("enemyA10"));
        enemyA10->setGeometry(QRect(50, 500, 50, 50));
        enemyA10->setMaximumSize(QSize(50, 50));
        enemyG10 = new QPushButton(centralwidget);
        enemyG10->setObjectName(QStringLiteral("enemyG10"));
        enemyG10->setGeometry(QRect(350, 500, 50, 50));
        enemyG10->setMaximumSize(QSize(50, 50));
        enemyI10 = new QPushButton(centralwidget);
        enemyI10->setObjectName(QStringLiteral("enemyI10"));
        enemyI10->setGeometry(QRect(450, 500, 50, 50));
        enemyI10->setMaximumSize(QSize(50, 50));
        enemyD10 = new QPushButton(centralwidget);
        enemyD10->setObjectName(QStringLiteral("enemyD10"));
        enemyD10->setGeometry(QRect(200, 500, 50, 50));
        enemyD10->setMaximumSize(QSize(50, 50));
        enemyB10 = new QPushButton(centralwidget);
        enemyB10->setObjectName(QStringLiteral("enemyB10"));
        enemyB10->setGeometry(QRect(100, 500, 50, 50));
        enemyB10->setMaximumSize(QSize(50, 50));
        enemyJ10 = new QPushButton(centralwidget);
        enemyJ10->setObjectName(QStringLiteral("enemyJ10"));
        enemyJ10->setGeometry(QRect(500, 500, 50, 50));
        enemyJ10->setMaximumSize(QSize(50, 50));
        meF1 = new QPushButton(centralwidget);
        meF1->setObjectName(QStringLiteral("meF1"));
        meF1->setGeometry(QRect(880, 50, 50, 50));
        meF1->setMaximumSize(QSize(50, 50));
        meC1 = new QPushButton(centralwidget);
        meC1->setObjectName(QStringLiteral("meC1"));
        meC1->setGeometry(QRect(730, 50, 50, 50));
        meC1->setMaximumSize(QSize(50, 50));
        meH1 = new QPushButton(centralwidget);
        meH1->setObjectName(QStringLiteral("meH1"));
        meH1->setGeometry(QRect(980, 50, 50, 50));
        meH1->setMaximumSize(QSize(50, 50));
        meE1 = new QPushButton(centralwidget);
        meE1->setObjectName(QStringLiteral("meE1"));
        meE1->setGeometry(QRect(830, 50, 50, 50));
        meE1->setMaximumSize(QSize(50, 50));
        meA1 = new QPushButton(centralwidget);
        meA1->setObjectName(QStringLiteral("meA1"));
        meA1->setGeometry(QRect(630, 50, 50, 50));
        meA1->setMaximumSize(QSize(50, 50));
        meG1 = new QPushButton(centralwidget);
        meG1->setObjectName(QStringLiteral("meG1"));
        meG1->setGeometry(QRect(930, 50, 50, 50));
        meG1->setMaximumSize(QSize(50, 50));
        meI1 = new QPushButton(centralwidget);
        meI1->setObjectName(QStringLiteral("meI1"));
        meI1->setGeometry(QRect(1030, 50, 50, 50));
        meI1->setMaximumSize(QSize(50, 50));
        meD1 = new QPushButton(centralwidget);
        meD1->setObjectName(QStringLiteral("meD1"));
        meD1->setGeometry(QRect(780, 50, 50, 50));
        meD1->setMaximumSize(QSize(50, 50));
        meB1 = new QPushButton(centralwidget);
        meB1->setObjectName(QStringLiteral("meB1"));
        meB1->setGeometry(QRect(680, 50, 50, 50));
        meB1->setMaximumSize(QSize(50, 50));
        meJ1 = new QPushButton(centralwidget);
        meJ1->setObjectName(QStringLiteral("meJ1"));
        meJ1->setGeometry(QRect(1080, 50, 50, 50));
        meJ1->setMaximumSize(QSize(50, 50));
        meF2 = new QPushButton(centralwidget);
        meF2->setObjectName(QStringLiteral("meF2"));
        meF2->setGeometry(QRect(880, 100, 50, 50));
        meF2->setMaximumSize(QSize(50, 50));
        meC2 = new QPushButton(centralwidget);
        meC2->setObjectName(QStringLiteral("meC2"));
        meC2->setGeometry(QRect(730, 100, 50, 50));
        meC2->setMaximumSize(QSize(50, 50));
        meH2 = new QPushButton(centralwidget);
        meH2->setObjectName(QStringLiteral("meH2"));
        meH2->setGeometry(QRect(980, 100, 50, 50));
        meH2->setMaximumSize(QSize(50, 50));
        meE2 = new QPushButton(centralwidget);
        meE2->setObjectName(QStringLiteral("meE2"));
        meE2->setGeometry(QRect(830, 100, 50, 50));
        meE2->setMaximumSize(QSize(50, 50));
        meA2 = new QPushButton(centralwidget);
        meA2->setObjectName(QStringLiteral("meA2"));
        meA2->setGeometry(QRect(630, 100, 50, 50));
        meA2->setMaximumSize(QSize(50, 50));
        meG2 = new QPushButton(centralwidget);
        meG2->setObjectName(QStringLiteral("meG2"));
        meG2->setGeometry(QRect(930, 100, 50, 50));
        meG2->setMaximumSize(QSize(50, 50));
        meI2 = new QPushButton(centralwidget);
        meI2->setObjectName(QStringLiteral("meI2"));
        meI2->setGeometry(QRect(1030, 100, 50, 50));
        meI2->setMaximumSize(QSize(50, 50));
        meD2 = new QPushButton(centralwidget);
        meD2->setObjectName(QStringLiteral("meD2"));
        meD2->setGeometry(QRect(780, 100, 50, 50));
        meD2->setMaximumSize(QSize(50, 50));
        meB2 = new QPushButton(centralwidget);
        meB2->setObjectName(QStringLiteral("meB2"));
        meB2->setGeometry(QRect(680, 100, 50, 50));
        meB2->setMaximumSize(QSize(50, 50));
        meJ2 = new QPushButton(centralwidget);
        meJ2->setObjectName(QStringLiteral("meJ2"));
        meJ2->setGeometry(QRect(1080, 100, 50, 50));
        meJ2->setMaximumSize(QSize(50, 50));
        meF3 = new QPushButton(centralwidget);
        meF3->setObjectName(QStringLiteral("meF3"));
        meF3->setGeometry(QRect(880, 150, 50, 50));
        meF3->setMaximumSize(QSize(50, 50));
        meC3 = new QPushButton(centralwidget);
        meC3->setObjectName(QStringLiteral("meC3"));
        meC3->setGeometry(QRect(730, 150, 50, 50));
        meC3->setMaximumSize(QSize(50, 50));
        meH3 = new QPushButton(centralwidget);
        meH3->setObjectName(QStringLiteral("meH3"));
        meH3->setGeometry(QRect(980, 150, 50, 50));
        meH3->setMaximumSize(QSize(50, 50));
        meE3 = new QPushButton(centralwidget);
        meE3->setObjectName(QStringLiteral("meE3"));
        meE3->setGeometry(QRect(830, 150, 50, 50));
        meE3->setMaximumSize(QSize(50, 50));
        meA3 = new QPushButton(centralwidget);
        meA3->setObjectName(QStringLiteral("meA3"));
        meA3->setGeometry(QRect(630, 150, 50, 50));
        meA3->setMaximumSize(QSize(50, 50));
        meG3 = new QPushButton(centralwidget);
        meG3->setObjectName(QStringLiteral("meG3"));
        meG3->setGeometry(QRect(930, 150, 50, 50));
        meG3->setMaximumSize(QSize(50, 50));
        meI3 = new QPushButton(centralwidget);
        meI3->setObjectName(QStringLiteral("meI3"));
        meI3->setGeometry(QRect(1030, 150, 50, 50));
        meI3->setMaximumSize(QSize(50, 50));
        meD3 = new QPushButton(centralwidget);
        meD3->setObjectName(QStringLiteral("meD3"));
        meD3->setGeometry(QRect(780, 150, 50, 50));
        meD3->setMaximumSize(QSize(50, 50));
        meB3 = new QPushButton(centralwidget);
        meB3->setObjectName(QStringLiteral("meB3"));
        meB3->setGeometry(QRect(680, 150, 50, 50));
        meB3->setMaximumSize(QSize(50, 50));
        meJ3 = new QPushButton(centralwidget);
        meJ3->setObjectName(QStringLiteral("meJ3"));
        meJ3->setGeometry(QRect(1080, 150, 50, 50));
        meJ3->setMaximumSize(QSize(50, 50));
        meF4 = new QPushButton(centralwidget);
        meF4->setObjectName(QStringLiteral("meF4"));
        meF4->setGeometry(QRect(880, 200, 50, 50));
        meF4->setMaximumSize(QSize(50, 50));
        meC4 = new QPushButton(centralwidget);
        meC4->setObjectName(QStringLiteral("meC4"));
        meC4->setGeometry(QRect(730, 200, 50, 50));
        meC4->setMaximumSize(QSize(50, 50));
        meH4 = new QPushButton(centralwidget);
        meH4->setObjectName(QStringLiteral("meH4"));
        meH4->setGeometry(QRect(980, 200, 50, 50));
        meH4->setMaximumSize(QSize(50, 50));
        meE4 = new QPushButton(centralwidget);
        meE4->setObjectName(QStringLiteral("meE4"));
        meE4->setGeometry(QRect(830, 200, 50, 50));
        meE4->setMaximumSize(QSize(50, 50));
        meA4 = new QPushButton(centralwidget);
        meA4->setObjectName(QStringLiteral("meA4"));
        meA4->setGeometry(QRect(630, 200, 50, 50));
        meA4->setMaximumSize(QSize(50, 50));
        meG4 = new QPushButton(centralwidget);
        meG4->setObjectName(QStringLiteral("meG4"));
        meG4->setGeometry(QRect(930, 200, 50, 50));
        meG4->setMaximumSize(QSize(50, 50));
        meI4 = new QPushButton(centralwidget);
        meI4->setObjectName(QStringLiteral("meI4"));
        meI4->setGeometry(QRect(1030, 200, 50, 50));
        meI4->setMaximumSize(QSize(50, 50));
        meD4 = new QPushButton(centralwidget);
        meD4->setObjectName(QStringLiteral("meD4"));
        meD4->setGeometry(QRect(780, 200, 50, 50));
        meD4->setMaximumSize(QSize(50, 50));
        meB4 = new QPushButton(centralwidget);
        meB4->setObjectName(QStringLiteral("meB4"));
        meB4->setGeometry(QRect(680, 200, 50, 50));
        meB4->setMaximumSize(QSize(50, 50));
        meJ4 = new QPushButton(centralwidget);
        meJ4->setObjectName(QStringLiteral("meJ4"));
        meJ4->setGeometry(QRect(1080, 200, 50, 50));
        meJ4->setMaximumSize(QSize(50, 50));
        meF5 = new QPushButton(centralwidget);
        meF5->setObjectName(QStringLiteral("meF5"));
        meF5->setGeometry(QRect(880, 250, 50, 50));
        meF5->setMaximumSize(QSize(50, 50));
        meC5 = new QPushButton(centralwidget);
        meC5->setObjectName(QStringLiteral("meC5"));
        meC5->setGeometry(QRect(730, 250, 50, 50));
        meC5->setMaximumSize(QSize(50, 50));
        meH5 = new QPushButton(centralwidget);
        meH5->setObjectName(QStringLiteral("meH5"));
        meH5->setGeometry(QRect(980, 250, 50, 50));
        meH5->setMaximumSize(QSize(50, 50));
        meE5 = new QPushButton(centralwidget);
        meE5->setObjectName(QStringLiteral("meE5"));
        meE5->setGeometry(QRect(830, 250, 50, 50));
        meE5->setMaximumSize(QSize(50, 50));
        meA5 = new QPushButton(centralwidget);
        meA5->setObjectName(QStringLiteral("meA5"));
        meA5->setGeometry(QRect(630, 250, 50, 50));
        meA5->setMaximumSize(QSize(50, 50));
        meG5 = new QPushButton(centralwidget);
        meG5->setObjectName(QStringLiteral("meG5"));
        meG5->setGeometry(QRect(930, 250, 50, 50));
        meG5->setMaximumSize(QSize(50, 50));
        meI5 = new QPushButton(centralwidget);
        meI5->setObjectName(QStringLiteral("meI5"));
        meI5->setGeometry(QRect(1030, 250, 50, 50));
        meI5->setMaximumSize(QSize(50, 50));
        meD5 = new QPushButton(centralwidget);
        meD5->setObjectName(QStringLiteral("meD5"));
        meD5->setGeometry(QRect(780, 250, 50, 50));
        meD5->setMaximumSize(QSize(50, 50));
        meB5 = new QPushButton(centralwidget);
        meB5->setObjectName(QStringLiteral("meB5"));
        meB5->setGeometry(QRect(680, 250, 50, 50));
        meB5->setMaximumSize(QSize(50, 50));
        meJ5 = new QPushButton(centralwidget);
        meJ5->setObjectName(QStringLiteral("meJ5"));
        meJ5->setGeometry(QRect(1080, 250, 50, 50));
        meJ5->setMaximumSize(QSize(50, 50));
        meF6 = new QPushButton(centralwidget);
        meF6->setObjectName(QStringLiteral("meF6"));
        meF6->setGeometry(QRect(880, 300, 50, 50));
        meF6->setMaximumSize(QSize(50, 50));
        meC6 = new QPushButton(centralwidget);
        meC6->setObjectName(QStringLiteral("meC6"));
        meC6->setGeometry(QRect(730, 300, 50, 50));
        meC6->setMaximumSize(QSize(50, 50));
        meH6 = new QPushButton(centralwidget);
        meH6->setObjectName(QStringLiteral("meH6"));
        meH6->setGeometry(QRect(980, 300, 50, 50));
        meH6->setMaximumSize(QSize(50, 50));
        meE6 = new QPushButton(centralwidget);
        meE6->setObjectName(QStringLiteral("meE6"));
        meE6->setGeometry(QRect(830, 300, 50, 50));
        meE6->setMaximumSize(QSize(50, 50));
        meA6 = new QPushButton(centralwidget);
        meA6->setObjectName(QStringLiteral("meA6"));
        meA6->setGeometry(QRect(630, 300, 50, 50));
        meA6->setMaximumSize(QSize(50, 50));
        meG6 = new QPushButton(centralwidget);
        meG6->setObjectName(QStringLiteral("meG6"));
        meG6->setGeometry(QRect(930, 300, 50, 50));
        meG6->setMaximumSize(QSize(50, 50));
        meI6 = new QPushButton(centralwidget);
        meI6->setObjectName(QStringLiteral("meI6"));
        meI6->setGeometry(QRect(1030, 300, 50, 50));
        meI6->setMaximumSize(QSize(50, 50));
        meD6 = new QPushButton(centralwidget);
        meD6->setObjectName(QStringLiteral("meD6"));
        meD6->setGeometry(QRect(780, 300, 50, 50));
        meD6->setMaximumSize(QSize(50, 50));
        meB6 = new QPushButton(centralwidget);
        meB6->setObjectName(QStringLiteral("meB6"));
        meB6->setGeometry(QRect(680, 300, 50, 50));
        meB6->setMaximumSize(QSize(50, 50));
        meJ6 = new QPushButton(centralwidget);
        meJ6->setObjectName(QStringLiteral("meJ6"));
        meJ6->setGeometry(QRect(1080, 300, 50, 50));
        meJ6->setMaximumSize(QSize(50, 50));
        meF7 = new QPushButton(centralwidget);
        meF7->setObjectName(QStringLiteral("meF7"));
        meF7->setGeometry(QRect(880, 350, 50, 50));
        meF7->setMaximumSize(QSize(50, 50));
        meC7 = new QPushButton(centralwidget);
        meC7->setObjectName(QStringLiteral("meC7"));
        meC7->setGeometry(QRect(730, 350, 50, 50));
        meC7->setMaximumSize(QSize(50, 50));
        meH7 = new QPushButton(centralwidget);
        meH7->setObjectName(QStringLiteral("meH7"));
        meH7->setGeometry(QRect(980, 350, 50, 50));
        meH7->setMaximumSize(QSize(50, 50));
        meE7 = new QPushButton(centralwidget);
        meE7->setObjectName(QStringLiteral("meE7"));
        meE7->setGeometry(QRect(830, 350, 50, 50));
        meE7->setMaximumSize(QSize(50, 50));
        meG7 = new QPushButton(centralwidget);
        meG7->setObjectName(QStringLiteral("meG7"));
        meG7->setGeometry(QRect(930, 350, 50, 50));
        meG7->setMaximumSize(QSize(50, 50));
        meI7 = new QPushButton(centralwidget);
        meI7->setObjectName(QStringLiteral("meI7"));
        meI7->setGeometry(QRect(1030, 350, 50, 50));
        meI7->setMaximumSize(QSize(50, 50));
        meD7 = new QPushButton(centralwidget);
        meD7->setObjectName(QStringLiteral("meD7"));
        meD7->setGeometry(QRect(780, 350, 50, 50));
        meD7->setMaximumSize(QSize(50, 50));
        meB7 = new QPushButton(centralwidget);
        meB7->setObjectName(QStringLiteral("meB7"));
        meB7->setGeometry(QRect(680, 350, 50, 50));
        meB7->setMaximumSize(QSize(50, 50));
        meJ7 = new QPushButton(centralwidget);
        meJ7->setObjectName(QStringLiteral("meJ7"));
        meJ7->setGeometry(QRect(1080, 350, 50, 50));
        meJ7->setMaximumSize(QSize(50, 50));
        meF8 = new QPushButton(centralwidget);
        meF8->setObjectName(QStringLiteral("meF8"));
        meF8->setGeometry(QRect(880, 400, 50, 50));
        meF8->setMaximumSize(QSize(50, 50));
        meC8 = new QPushButton(centralwidget);
        meC8->setObjectName(QStringLiteral("meC8"));
        meC8->setGeometry(QRect(730, 400, 50, 50));
        meC8->setMaximumSize(QSize(50, 50));
        meH8 = new QPushButton(centralwidget);
        meH8->setObjectName(QStringLiteral("meH8"));
        meH8->setGeometry(QRect(980, 400, 50, 50));
        meH8->setMaximumSize(QSize(50, 50));
        meE8 = new QPushButton(centralwidget);
        meE8->setObjectName(QStringLiteral("meE8"));
        meE8->setGeometry(QRect(830, 400, 50, 50));
        meE8->setMaximumSize(QSize(50, 50));
        meA8 = new QPushButton(centralwidget);
        meA8->setObjectName(QStringLiteral("meA8"));
        meA8->setGeometry(QRect(630, 400, 50, 50));
        meA8->setMaximumSize(QSize(50, 50));
        meG8 = new QPushButton(centralwidget);
        meG8->setObjectName(QStringLiteral("meG8"));
        meG8->setGeometry(QRect(930, 400, 50, 50));
        meG8->setMaximumSize(QSize(50, 50));
        meI8 = new QPushButton(centralwidget);
        meI8->setObjectName(QStringLiteral("meI8"));
        meI8->setGeometry(QRect(1030, 400, 50, 50));
        meI8->setMaximumSize(QSize(50, 50));
        meD8 = new QPushButton(centralwidget);
        meD8->setObjectName(QStringLiteral("meD8"));
        meD8->setGeometry(QRect(780, 400, 50, 50));
        meD8->setMaximumSize(QSize(50, 50));
        meB8 = new QPushButton(centralwidget);
        meB8->setObjectName(QStringLiteral("meB8"));
        meB8->setGeometry(QRect(680, 400, 50, 50));
        meB8->setMaximumSize(QSize(50, 50));
        meJ8 = new QPushButton(centralwidget);
        meJ8->setObjectName(QStringLiteral("meJ8"));
        meJ8->setGeometry(QRect(1080, 400, 50, 50));
        meJ8->setMaximumSize(QSize(50, 50));
        meF9 = new QPushButton(centralwidget);
        meF9->setObjectName(QStringLiteral("meF9"));
        meF9->setGeometry(QRect(880, 450, 50, 50));
        meF9->setMaximumSize(QSize(50, 50));
        meC9 = new QPushButton(centralwidget);
        meC9->setObjectName(QStringLiteral("meC9"));
        meC9->setGeometry(QRect(730, 450, 50, 50));
        meC9->setMaximumSize(QSize(50, 50));
        meH9 = new QPushButton(centralwidget);
        meH9->setObjectName(QStringLiteral("meH9"));
        meH9->setGeometry(QRect(980, 450, 50, 50));
        meH9->setMaximumSize(QSize(50, 50));
        meE9 = new QPushButton(centralwidget);
        meE9->setObjectName(QStringLiteral("meE9"));
        meE9->setGeometry(QRect(830, 450, 50, 50));
        meE9->setMaximumSize(QSize(50, 50));
        meA9 = new QPushButton(centralwidget);
        meA9->setObjectName(QStringLiteral("meA9"));
        meA9->setGeometry(QRect(630, 450, 50, 50));
        meA9->setMaximumSize(QSize(50, 50));
        meG9 = new QPushButton(centralwidget);
        meG9->setObjectName(QStringLiteral("meG9"));
        meG9->setGeometry(QRect(930, 450, 50, 50));
        meG9->setMaximumSize(QSize(50, 50));
        meI9 = new QPushButton(centralwidget);
        meI9->setObjectName(QStringLiteral("meI9"));
        meI9->setGeometry(QRect(1030, 450, 50, 50));
        meI9->setMaximumSize(QSize(50, 50));
        meD9 = new QPushButton(centralwidget);
        meD9->setObjectName(QStringLiteral("meD9"));
        meD9->setGeometry(QRect(780, 450, 50, 50));
        meD9->setMaximumSize(QSize(50, 50));
        meB9 = new QPushButton(centralwidget);
        meB9->setObjectName(QStringLiteral("meB9"));
        meB9->setGeometry(QRect(680, 450, 50, 50));
        meB9->setMaximumSize(QSize(50, 50));
        meJ9 = new QPushButton(centralwidget);
        meJ9->setObjectName(QStringLiteral("meJ9"));
        meJ9->setGeometry(QRect(1080, 450, 50, 50));
        meJ9->setMaximumSize(QSize(50, 50));
        meF10 = new QPushButton(centralwidget);
        meF10->setObjectName(QStringLiteral("meF10"));
        meF10->setGeometry(QRect(880, 500, 50, 50));
        meF10->setMaximumSize(QSize(50, 50));
        meC10 = new QPushButton(centralwidget);
        meC10->setObjectName(QStringLiteral("meC10"));
        meC10->setGeometry(QRect(730, 500, 50, 50));
        meC10->setMaximumSize(QSize(50, 50));
        meH10 = new QPushButton(centralwidget);
        meH10->setObjectName(QStringLiteral("meH10"));
        meH10->setGeometry(QRect(980, 500, 50, 50));
        meH10->setMaximumSize(QSize(50, 50));
        meE10 = new QPushButton(centralwidget);
        meE10->setObjectName(QStringLiteral("meE10"));
        meE10->setGeometry(QRect(830, 500, 50, 50));
        meE10->setMaximumSize(QSize(50, 50));
        meA10 = new QPushButton(centralwidget);
        meA10->setObjectName(QStringLiteral("meA10"));
        meA10->setGeometry(QRect(630, 500, 50, 50));
        meA10->setMaximumSize(QSize(50, 50));
        meG10 = new QPushButton(centralwidget);
        meG10->setObjectName(QStringLiteral("meG10"));
        meG10->setGeometry(QRect(930, 500, 50, 50));
        meG10->setMaximumSize(QSize(50, 50));
        meI10 = new QPushButton(centralwidget);
        meI10->setObjectName(QStringLiteral("meI10"));
        meI10->setGeometry(QRect(1030, 500, 50, 50));
        meI10->setMaximumSize(QSize(50, 50));
        meD10 = new QPushButton(centralwidget);
        meD10->setObjectName(QStringLiteral("meD10"));
        meD10->setGeometry(QRect(780, 500, 50, 50));
        meD10->setMaximumSize(QSize(50, 50));
        meB10 = new QPushButton(centralwidget);
        meB10->setObjectName(QStringLiteral("meB10"));
        meB10->setGeometry(QRect(680, 500, 50, 50));
        meB10->setMaximumSize(QSize(50, 50));
        meJ10 = new QPushButton(centralwidget);
        meJ10->setObjectName(QStringLiteral("meJ10"));
        meJ10->setGeometry(QRect(1080, 500, 50, 50));
        meJ10->setMaximumSize(QSize(50, 50));
        battleship1 = new QPushButton(centralwidget);
        battleship1->setObjectName(QStringLiteral("battleship1"));
        battleship1->setGeometry(QRect(1200, 110, 50, 50));
        battleship1->setMinimumSize(QSize(50, 50));
        battleship1->setMaximumSize(QSize(50, 50));
        battleship2 = new QPushButton(centralwidget);
        battleship2->setObjectName(QStringLiteral("battleship2"));
        battleship2->setGeometry(QRect(1200, 160, 100, 50));
        battleship2->setMinimumSize(QSize(100, 50));
        battleship2->setMaximumSize(QSize(100, 50));
        battleship3_1 = new QPushButton(centralwidget);
        battleship3_1->setObjectName(QStringLiteral("battleship3_1"));
        battleship3_1->setGeometry(QRect(1200, 210, 150, 50));
        battleship3_1->setMinimumSize(QSize(150, 50));
        battleship3_1->setMaximumSize(QSize(150, 50));
        battleship3_2 = new QPushButton(centralwidget);
        battleship3_2->setObjectName(QStringLiteral("battleship3_2"));
        battleship3_2->setGeometry(QRect(1200, 260, 150, 50));
        battleship3_2->setMinimumSize(QSize(150, 50));
        battleship3_2->setMaximumSize(QSize(150, 50));
        battleship4 = new QPushButton(centralwidget);
        battleship4->setObjectName(QStringLiteral("battleship4"));
        battleship4->setGeometry(QRect(1200, 310, 200, 50));
        battleship4->setMinimumSize(QSize(200, 50));
        battleship4->setMaximumSize(QSize(200, 50));
        battleship5 = new QPushButton(centralwidget);
        battleship5->setObjectName(QStringLiteral("battleship5"));
        battleship5->setGeometry(QRect(1200, 360, 250, 50));
        battleship5->setMinimumSize(QSize(250, 50));
        battleship5->setMaximumSize(QSize(250, 50));
        label = new QLabel(centralwidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(240, 560, 131, 51));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(850, 560, 61, 51));
        meA7 = new QPushButton(centralwidget);
        meA7->setObjectName(QStringLiteral("meA7"));
        meA7->setGeometry(QRect(630, 350, 50, 50));
        meA7->setMaximumSize(QSize(50, 50));
        lineEdit = new QLineEdit(centralwidget);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setEnabled(false);
        lineEdit->setGeometry(QRect(0, 50, 50, 50));
        lineEdit_2 = new QLineEdit(centralwidget);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setEnabled(false);
        lineEdit_2->setGeometry(QRect(0, 100, 50, 50));
        lineEdit_3 = new QLineEdit(centralwidget);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setEnabled(false);
        lineEdit_3->setGeometry(QRect(0, 200, 50, 50));
        lineEdit_4 = new QLineEdit(centralwidget);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setEnabled(false);
        lineEdit_4->setGeometry(QRect(0, 150, 50, 50));
        lineEdit_5 = new QLineEdit(centralwidget);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setEnabled(false);
        lineEdit_5->setGeometry(QRect(0, 300, 50, 50));
        lineEdit_6 = new QLineEdit(centralwidget);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setEnabled(false);
        lineEdit_6->setGeometry(QRect(0, 250, 50, 50));
        lineEdit_7 = new QLineEdit(centralwidget);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setEnabled(false);
        lineEdit_7->setGeometry(QRect(0, 400, 50, 50));
        lineEdit_8 = new QLineEdit(centralwidget);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setEnabled(false);
        lineEdit_8->setGeometry(QRect(0, 350, 50, 50));
        lineEdit_9 = new QLineEdit(centralwidget);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setEnabled(false);
        lineEdit_9->setGeometry(QRect(0, 500, 50, 50));
        lineEdit_10 = new QLineEdit(centralwidget);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setEnabled(false);
        lineEdit_10->setGeometry(QRect(0, 450, 50, 50));
        lineEdit_11 = new QLineEdit(centralwidget);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setEnabled(false);
        lineEdit_11->setGeometry(QRect(580, 500, 50, 50));
        lineEdit_12 = new QLineEdit(centralwidget);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setEnabled(false);
        lineEdit_12->setGeometry(QRect(580, 400, 50, 50));
        lineEdit_13 = new QLineEdit(centralwidget);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setEnabled(false);
        lineEdit_13->setGeometry(QRect(580, 450, 50, 50));
        lineEdit_14 = new QLineEdit(centralwidget);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setEnabled(false);
        lineEdit_14->setGeometry(QRect(580, 200, 50, 50));
        lineEdit_15 = new QLineEdit(centralwidget);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setEnabled(false);
        lineEdit_15->setGeometry(QRect(580, 150, 50, 50));
        lineEdit_16 = new QLineEdit(centralwidget);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setEnabled(false);
        lineEdit_16->setGeometry(QRect(580, 300, 50, 50));
        lineEdit_17 = new QLineEdit(centralwidget);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setEnabled(false);
        lineEdit_17->setGeometry(QRect(580, 350, 50, 50));
        lineEdit_18 = new QLineEdit(centralwidget);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setEnabled(false);
        lineEdit_18->setGeometry(QRect(580, 100, 50, 50));
        lineEdit_19 = new QLineEdit(centralwidget);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setEnabled(false);
        lineEdit_19->setGeometry(QRect(580, 250, 50, 50));
        lineEdit_20 = new QLineEdit(centralwidget);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setEnabled(false);
        lineEdit_20->setGeometry(QRect(580, 50, 50, 50));
        lineEdit_21 = new QLineEdit(centralwidget);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setEnabled(false);
        lineEdit_21->setGeometry(QRect(50, 0, 50, 50));
        lineEdit_22 = new QLineEdit(centralwidget);
        lineEdit_22->setObjectName(QStringLiteral("lineEdit_22"));
        lineEdit_22->setEnabled(false);
        lineEdit_22->setGeometry(QRect(100, 0, 50, 50));
        lineEdit_23 = new QLineEdit(centralwidget);
        lineEdit_23->setObjectName(QStringLiteral("lineEdit_23"));
        lineEdit_23->setEnabled(false);
        lineEdit_23->setGeometry(QRect(200, 0, 50, 50));
        lineEdit_24 = new QLineEdit(centralwidget);
        lineEdit_24->setObjectName(QStringLiteral("lineEdit_24"));
        lineEdit_24->setEnabled(false);
        lineEdit_24->setGeometry(QRect(150, 0, 50, 50));
        lineEdit_25 = new QLineEdit(centralwidget);
        lineEdit_25->setObjectName(QStringLiteral("lineEdit_25"));
        lineEdit_25->setEnabled(false);
        lineEdit_25->setGeometry(QRect(300, 0, 50, 50));
        lineEdit_26 = new QLineEdit(centralwidget);
        lineEdit_26->setObjectName(QStringLiteral("lineEdit_26"));
        lineEdit_26->setEnabled(false);
        lineEdit_26->setGeometry(QRect(250, 0, 50, 50));
        lineEdit_27 = new QLineEdit(centralwidget);
        lineEdit_27->setObjectName(QStringLiteral("lineEdit_27"));
        lineEdit_27->setEnabled(false);
        lineEdit_27->setGeometry(QRect(400, 0, 50, 50));
        lineEdit_28 = new QLineEdit(centralwidget);
        lineEdit_28->setObjectName(QStringLiteral("lineEdit_28"));
        lineEdit_28->setEnabled(false);
        lineEdit_28->setGeometry(QRect(350, 0, 50, 50));
        lineEdit_29 = new QLineEdit(centralwidget);
        lineEdit_29->setObjectName(QStringLiteral("lineEdit_29"));
        lineEdit_29->setEnabled(false);
        lineEdit_29->setGeometry(QRect(500, 0, 50, 50));
        lineEdit_30 = new QLineEdit(centralwidget);
        lineEdit_30->setObjectName(QStringLiteral("lineEdit_30"));
        lineEdit_30->setEnabled(false);
        lineEdit_30->setGeometry(QRect(450, 0, 50, 50));
        lineEdit_31 = new QLineEdit(centralwidget);
        lineEdit_31->setObjectName(QStringLiteral("lineEdit_31"));
        lineEdit_31->setEnabled(false);
        lineEdit_31->setGeometry(QRect(730, 0, 50, 50));
        lineEdit_32 = new QLineEdit(centralwidget);
        lineEdit_32->setObjectName(QStringLiteral("lineEdit_32"));
        lineEdit_32->setEnabled(false);
        lineEdit_32->setGeometry(QRect(1080, 0, 50, 50));
        lineEdit_33 = new QLineEdit(centralwidget);
        lineEdit_33->setObjectName(QStringLiteral("lineEdit_33"));
        lineEdit_33->setEnabled(false);
        lineEdit_33->setGeometry(QRect(680, 0, 50, 50));
        lineEdit_34 = new QLineEdit(centralwidget);
        lineEdit_34->setObjectName(QStringLiteral("lineEdit_34"));
        lineEdit_34->setEnabled(false);
        lineEdit_34->setGeometry(QRect(930, 0, 50, 50));
        lineEdit_35 = new QLineEdit(centralwidget);
        lineEdit_35->setObjectName(QStringLiteral("lineEdit_35"));
        lineEdit_35->setEnabled(false);
        lineEdit_35->setGeometry(QRect(830, 0, 50, 50));
        lineEdit_36 = new QLineEdit(centralwidget);
        lineEdit_36->setObjectName(QStringLiteral("lineEdit_36"));
        lineEdit_36->setEnabled(false);
        lineEdit_36->setGeometry(QRect(780, 0, 50, 50));
        lineEdit_37 = new QLineEdit(centralwidget);
        lineEdit_37->setObjectName(QStringLiteral("lineEdit_37"));
        lineEdit_37->setEnabled(false);
        lineEdit_37->setGeometry(QRect(1030, 0, 50, 50));
        lineEdit_38 = new QLineEdit(centralwidget);
        lineEdit_38->setObjectName(QStringLiteral("lineEdit_38"));
        lineEdit_38->setEnabled(false);
        lineEdit_38->setGeometry(QRect(980, 0, 50, 50));
        lineEdit_39 = new QLineEdit(centralwidget);
        lineEdit_39->setObjectName(QStringLiteral("lineEdit_39"));
        lineEdit_39->setEnabled(false);
        lineEdit_39->setGeometry(QRect(630, 0, 50, 50));
        lineEdit_40 = new QLineEdit(centralwidget);
        lineEdit_40->setObjectName(QStringLiteral("lineEdit_40"));
        lineEdit_40->setEnabled(false);
        lineEdit_40->setGeometry(QRect(880, 0, 50, 50));
        lineEdit_41 = new QLineEdit(centralwidget);
        lineEdit_41->setObjectName(QStringLiteral("lineEdit_41"));
        lineEdit_41->setEnabled(false);
        lineEdit_41->setGeometry(QRect(1230, 420, 201, 50));
        QFont font;
        font.setPointSize(12);
        lineEdit_41->setFont(font);
        MainGame->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainGame);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1550, 26));
        MainGame->setMenuBar(menubar);
        statusbar = new QStatusBar(MainGame);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainGame->setStatusBar(statusbar);

        retranslateUi(MainGame);

        QMetaObject::connectSlotsByName(MainGame);
    } // setupUi

    void retranslateUi(QMainWindow *MainGame)
    {
        MainGame->setWindowTitle(QApplication::translate("MainGame", "MainWindow", nullptr));
        enemyA1->setText(QString());
        enemyB1->setText(QString());
        enemyC1->setText(QString());
        enemyD1->setText(QString());
        enemyE1->setText(QString());
        enemyF1->setText(QString());
        enemyG1->setText(QString());
        enemyH1->setText(QString());
        enemyI1->setText(QString());
        enemyJ1->setText(QString());
        enemyF2->setText(QString());
        enemyC2->setText(QString());
        enemyH2->setText(QString());
        enemyE2->setText(QString());
        enemyA2->setText(QString());
        enemyG2->setText(QString());
        enemyI2->setText(QString());
        enemyD2->setText(QString());
        enemyB2->setText(QString());
        enemyJ2->setText(QString());
        enemyF3->setText(QString());
        enemyC3->setText(QString());
        enemyH3->setText(QString());
        enemyE3->setText(QString());
        enemyA3->setText(QString());
        enemyG3->setText(QString());
        enemyI3->setText(QString());
        enemyD3->setText(QString());
        enemyB3->setText(QString());
        enemyJ3->setText(QString());
        enemyF4->setText(QString());
        enemyC4->setText(QString());
        enemyH4->setText(QString());
        enemyE4->setText(QString());
        enemyA4->setText(QString());
        enemyG4->setText(QString());
        enemyI4->setText(QString());
        enemyD4->setText(QString());
        enemyB4->setText(QString());
        enemyJ4->setText(QString());
        enemyF5->setText(QString());
        enemyC5->setText(QString());
        enemyH5->setText(QString());
        enemyE5->setText(QString());
        enemyA5->setText(QString());
        enemyG5->setText(QString());
        enemyI5->setText(QString());
        enemyD5->setText(QString());
        enemyB5->setText(QString());
        enemyJ5->setText(QString());
        enemyF6->setText(QString());
        enemyC6->setText(QString());
        enemyH6->setText(QString());
        enemyE6->setText(QString());
        enemyA6->setText(QString());
        enemyG6->setText(QString());
        enemyI6->setText(QString());
        enemyD6->setText(QString());
        enemyB6->setText(QString());
        enemyJ6->setText(QString());
        enemyF7->setText(QString());
        enemyC7->setText(QString());
        enemyH7->setText(QString());
        enemyE7->setText(QString());
        enemyA7->setText(QString());
        enemyG7->setText(QString());
        enemyI7->setText(QString());
        enemyD7->setText(QString());
        enemyB7->setText(QString());
        enemyJ7->setText(QString());
        enemyF8->setText(QString());
        enemyC8->setText(QString());
        enemyH8->setText(QString());
        enemyE8->setText(QString());
        enemyA8->setText(QString());
        enemyG8->setText(QString());
        enemyI8->setText(QString());
        enemyD8->setText(QString());
        enemyB8->setText(QString());
        enemyJ8->setText(QString());
        enemyF9->setText(QString());
        enemyC9->setText(QString());
        enemyH9->setText(QString());
        enemyE9->setText(QString());
        enemyA9->setText(QString());
        enemyG9->setText(QString());
        enemyI9->setText(QString());
        enemyD9->setText(QString());
        enemyB9->setText(QString());
        enemyJ9->setText(QString());
        enemyF10->setText(QString());
        enemyC10->setText(QString());
        enemyH10->setText(QString());
        enemyE10->setText(QString());
        enemyA10->setText(QString());
        enemyG10->setText(QString());
        enemyI10->setText(QString());
        enemyD10->setText(QString());
        enemyB10->setText(QString());
        enemyJ10->setText(QString());
        meF1->setText(QString());
        meC1->setText(QString());
        meH1->setText(QString());
        meE1->setText(QString());
        meA1->setText(QString());
        meG1->setText(QString());
        meI1->setText(QString());
        meD1->setText(QString());
        meB1->setText(QString());
        meJ1->setText(QString());
        meF2->setText(QString());
        meC2->setText(QString());
        meH2->setText(QString());
        meE2->setText(QString());
        meA2->setText(QString());
        meG2->setText(QString());
        meI2->setText(QString());
        meD2->setText(QString());
        meB2->setText(QString());
        meJ2->setText(QString());
        meF3->setText(QString());
        meC3->setText(QString());
        meH3->setText(QString());
        meE3->setText(QString());
        meA3->setText(QString());
        meG3->setText(QString());
        meI3->setText(QString());
        meD3->setText(QString());
        meB3->setText(QString());
        meJ3->setText(QString());
        meF4->setText(QString());
        meC4->setText(QString());
        meH4->setText(QString());
        meE4->setText(QString());
        meA4->setText(QString());
        meG4->setText(QString());
        meI4->setText(QString());
        meD4->setText(QString());
        meB4->setText(QString());
        meJ4->setText(QString());
        meF5->setText(QString());
        meC5->setText(QString());
        meH5->setText(QString());
        meE5->setText(QString());
        meA5->setText(QString());
        meG5->setText(QString());
        meI5->setText(QString());
        meD5->setText(QString());
        meB5->setText(QString());
        meJ5->setText(QString());
        meF6->setText(QString());
        meC6->setText(QString());
        meH6->setText(QString());
        meE6->setText(QString());
        meA6->setText(QString());
        meG6->setText(QString());
        meI6->setText(QString());
        meD6->setText(QString());
        meB6->setText(QString());
        meJ6->setText(QString());
        meF7->setText(QString());
        meC7->setText(QString());
        meH7->setText(QString());
        meE7->setText(QString());
        meG7->setText(QString());
        meI7->setText(QString());
        meD7->setText(QString());
        meB7->setText(QString());
        meJ7->setText(QString());
        meF8->setText(QString());
        meC8->setText(QString());
        meH8->setText(QString());
        meE8->setText(QString());
        meA8->setText(QString());
        meG8->setText(QString());
        meI8->setText(QString());
        meD8->setText(QString());
        meB8->setText(QString());
        meJ8->setText(QString());
        meF9->setText(QString());
        meC9->setText(QString());
        meH9->setText(QString());
        meE9->setText(QString());
        meA9->setText(QString());
        meG9->setText(QString());
        meI9->setText(QString());
        meD9->setText(QString());
        meB9->setText(QString());
        meJ9->setText(QString());
        meF10->setText(QString());
        meC10->setText(QString());
        meH10->setText(QString());
        meE10->setText(QString());
        meA10->setText(QString());
        meG10->setText(QString());
        meI10->setText(QString());
        meD10->setText(QString());
        meB10->setText(QString());
        meJ10->setText(QString());
        battleship1->setText(QString());
        battleship2->setText(QString());
        battleship3_1->setText(QString());
        battleship3_2->setText(QString());
        battleship4->setText(QString());
        battleship5->setText(QString());
        label->setText(QApplication::translate("MainGame", "<html><head/><body><p><span style=\" font-size:12pt;\">Enemy player</span></p></body></html>", nullptr));
        label_2->setText(QApplication::translate("MainGame", "<html><head/><body><p><span style=\" font-size:12pt;\">Player</span></p></body></html>", nullptr));
        meA7->setText(QString());
        lineEdit->setText(QApplication::translate("MainGame", "    1 ", nullptr));
        lineEdit_2->setText(QApplication::translate("MainGame", "    2 ", nullptr));
        lineEdit_3->setText(QApplication::translate("MainGame", "    4 ", nullptr));
        lineEdit_4->setText(QApplication::translate("MainGame", "    3 ", nullptr));
        lineEdit_5->setText(QApplication::translate("MainGame", "    6 ", nullptr));
        lineEdit_6->setText(QApplication::translate("MainGame", "    5 ", nullptr));
        lineEdit_7->setText(QApplication::translate("MainGame", "    8 ", nullptr));
        lineEdit_8->setText(QApplication::translate("MainGame", "    7 ", nullptr));
        lineEdit_9->setText(QApplication::translate("MainGame", "    10 ", nullptr));
        lineEdit_10->setText(QApplication::translate("MainGame", "    9 ", nullptr));
        lineEdit_11->setText(QApplication::translate("MainGame", "    10 ", nullptr));
        lineEdit_12->setText(QApplication::translate("MainGame", "    8 ", nullptr));
        lineEdit_13->setText(QApplication::translate("MainGame", "    9 ", nullptr));
        lineEdit_14->setText(QApplication::translate("MainGame", "    4 ", nullptr));
        lineEdit_15->setText(QApplication::translate("MainGame", "    3 ", nullptr));
        lineEdit_16->setText(QApplication::translate("MainGame", "    6 ", nullptr));
        lineEdit_17->setText(QApplication::translate("MainGame", "    7 ", nullptr));
        lineEdit_18->setText(QApplication::translate("MainGame", "    2 ", nullptr));
        lineEdit_19->setText(QApplication::translate("MainGame", "    5 ", nullptr));
        lineEdit_20->setText(QApplication::translate("MainGame", "    1 ", nullptr));
        lineEdit_21->setText(QApplication::translate("MainGame", "     A ", nullptr));
        lineEdit_22->setText(QApplication::translate("MainGame", "     B ", nullptr));
        lineEdit_23->setText(QApplication::translate("MainGame", "     D ", nullptr));
        lineEdit_24->setText(QApplication::translate("MainGame", "     C ", nullptr));
        lineEdit_25->setText(QApplication::translate("MainGame", "     F ", nullptr));
        lineEdit_26->setText(QApplication::translate("MainGame", "     E ", nullptr));
        lineEdit_27->setText(QApplication::translate("MainGame", "     H ", nullptr));
        lineEdit_28->setText(QApplication::translate("MainGame", "     G ", nullptr));
        lineEdit_29->setText(QApplication::translate("MainGame", "     J ", nullptr));
        lineEdit_30->setText(QApplication::translate("MainGame", "     I ", nullptr));
        lineEdit_31->setText(QApplication::translate("MainGame", "     C ", nullptr));
        lineEdit_32->setText(QApplication::translate("MainGame", "     J ", nullptr));
        lineEdit_33->setText(QApplication::translate("MainGame", "     B ", nullptr));
        lineEdit_34->setText(QApplication::translate("MainGame", "     G ", nullptr));
        lineEdit_35->setText(QApplication::translate("MainGame", "     E ", nullptr));
        lineEdit_36->setText(QApplication::translate("MainGame", "     D ", nullptr));
        lineEdit_37->setText(QApplication::translate("MainGame", "     I ", nullptr));
        lineEdit_38->setText(QApplication::translate("MainGame", "     H ", nullptr));
        lineEdit_39->setText(QApplication::translate("MainGame", "     A ", nullptr));
        lineEdit_40->setText(QApplication::translate("MainGame", "     F ", nullptr));
        lineEdit_41->setText(QApplication::translate("MainGame", "Place all 6 battleships", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainGame: public Ui_MainGame {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINGAME_H
